### PR TITLE
Feature add canid file structure

### LINKED ISSUE #12: Standardize CAN ID/message allocation and usage.
We are only using the google form for managing CAN IDs and message frames. While this google doc and be updated, it does not necessarily mean that any code reflects this in the main module.

We should create some scripts that will generate C header files with constant #define for each message and data bit. These files can be easily re-generated to reflect any updates on the google sheet or CSV file in this repo.

Example snippet of C header file:

'CAN_CONSTANTS.h'
...
#define ACCEL_CAN_ID 0x7a1
#define ACCEL_TYPE_START_BYTE 0
#define ACCEL_TYPE_END_BYTE 1
#define ACCEL_DATA_START_BYTE 2
#define ACCEL_DATA_END_BYTE 5
#define ACCEL_TIME_START_BYTE 6
#define ACCEL_TIME_END_BYTE 7
...

### PR DESCRIPTION
**Pull request by AdamBusch**
Resolves #12 by grouping and finalizing CAN id management. 
We need to switch from addressing by bytes to bits in order to allow for messages to occupy less than 8 bits.
(Example: enable/disable flags for sensors)

### CODE REVIEW

**Comment by jacklecroy** [comment]
I'm going to clean up the update script and the header script and then merge them into one.

**Comment by raymonddong** [comment]
bit manipulation
very cool adam!

**Comment by RyanSchw** [comment]
What's the status of this? If this is ready to review, please request review from mergers/reviewers.

**Comment by RyanSchw** [comment]
Resolves #12

**Review by RyanSchw — APPROVED** [review]

**Pull request merged**
