### PR TITLE
Add pipenv to manage dependencies, solves #9

### PR DESCRIPTION
**Pull request by AdamBusch**
pipenv ensures that you can run the python files with the correct pip
modules on different systems. While not as complete as a docker
solution, this will solve our needs for this simple project.

### CODE REVIEW

**Comment by jacklecroy** [comment]
It has virtualenv support and gets automatically updated when you use it

**Comment by RyanSchw** [comment]
Can you add setup procedures to either `README.md` or wiki? Just a simple how-to-use.

**Comment by jacklecroy** [comment]
Sure, I'll put it in the readme

**Review by RyanSchw — DISMISSED** [review]

**Review by bsmrdel — DISMISSED** [review]
Looks fantastic

**Review by RyanSchw — DISMISSED** [review]

**Comment by RyanSchw** [comment]
Are you guys still using pipenv? Would be good to start using this since `3.7.4` is now the default install instead of `3.6`

**Comment by RyanSchw** [comment]
@AdamBusch @jacklecroy ,

Thoughts on starting to use docker for everything we can manage? https://www.freecodecamp.org/news/put-your-dev-env-in-github/amp/

Would remove the need for this PR -- [essentially does the same thing as `venv` it seems](https://stackoverflow.com/questions/27017715/does-virtualenv-serve-a-purpose-in-production-when-using-docker), but we could use this as a test for all other repos. End goal being all development (even for car code) is done using this method.

**Comment by jacklecroy** [comment]
Yes, Docker would be a good solution. We can start to implement it soon.

**Comment by RyanSchw** [comment]
Will switch to using Docker stuff

**Review by RyanSchw — APPROVED** [review]

**Pull request merged**
